#pragma once
#define VIAL_KEYBOARD_UID {0x7F, 0xE0, 0x4F, 0x7F, 0x44, 0x1C, 0x9A, 0x4F}
#define DYNAMIC_KEYMAP_LAYER_COUNT 4
#define VIAL_ENCODER_DEFAULT {KC_VOLD, KC_VOLU, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS}
#define VIAL_TAP_DANCE_ENTRIES 4
#define VIAL_COMBO_ENTRIES 4
