# CAPS_WORD_ENABLE = no
# OS_DETECTION_ENABLE = no

# OLED_ENABLE = no

# WPM_ENABLE = no
#
# HAPTIC_ENABLE = no

ENCODER_MAP_ENABLE = no
BOOTMAGIC_ENABLE = yes
MAGIC_ENABLE = yes
OS_DETECTION_ENABLE = yes
DYNAMIC_MACRO_ENABLE = no
CAPS_WORD_ENABLE = yes
