#define TAPPING_TERM 175

#define COMBO_COUNT 12
#define COMBO_TERM 165

// Mouse key speed and acceleration.
#undef MOUSEKEY_DELAY
#define MOUSEKEY_DELAY          0
#undef MOUSEKEY_INTERVAL
#define MOUSEKEY_INTERVAL       16
#undef MOUSEKEY_WHEEL_DELAY
#define MOUSEKEY_WHEEL_DELAY    0
#undef MOUSEKEY_MAX_SPEED
#define MOUSEKEY_MAX_SPEED      5
#undef MOUSEKEY_TIME_TO_MAX
#define MOUSEKEY_TIME_TO_MAX    64

// #undef RGBLIGHT_HUE_STEP
// #define RGBLIGHT_HUE_STEP 2
// #undef RGBLIGHT_SAT_STEP
// #define RGBLIGHT_SAT_STEP 2
// #undef RGBLIGHT_VAL_STEP
// #define RGBLIGHT_VAL_STEP 2
