#pragma once
#define VIAL_KEYBOARD_UID {0x1A, 0x09, 0x3F, 0x6C, 0xA8, 0xB9, 0xCA, 0x12}
#define DYNAMIC_KEYMAP_LAYER_COUNT 4
#define VIAL_ENCODER_DEFAULT {KC_VOLD, KC_VOLU, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS}
#define VIAL_TAP_DANCE_ENTRIES 4
#define VIAL_COMBO_ENTRIES 4
